
// Group existing labels and controls without changing their identifiers or events.
document.querySelectorAll('#caseForm > label').forEach(label=>{
 const control=label.nextElementSibling;
 const field=document.createElement('div');field.className='field';
 label.before(field);field.append(label,control);
});
const footer=document.createElement('footer');footer.className='workspace-footer';
footer.innerHTML='<strong>Lili Sincronia · Coordinacion quirurgica</strong><span>Fundacion Valle del Lili · Principal y Limonar</span>';
document.querySelector('main').append(footer);





let cases=[],seq=1;const $=id=>document.getElementById(id);const rank={emergente:0,urgente:1,urg_relativa:2,electiva:3};const turnover=20;
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}function esc(v){return String(v).replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function selectedDay(){let d=new Date(`${$('date').value}T12:00:00`);return days[(d.getDay()+6)%7]}function activeSlots(){const site=$('site').value,di=days.indexOf(selectedDay()),source=regularities[site],rooms=[...new Set(source.map(x=>x[0]))];let slots=[];rooms.forEach(room=>['AM','PM'].forEach(shift=>{let entry=source.find(x=>x[0]===room&&x[1]===shift),rule=entry&&entry[2][di]?entry[2][di]:'Sin regularidad definida';slots.push({id:`${room}-${shift}`,room,shift,rule,cap:360,items:[]})}));let nightRooms=site==='Principal'?8:3;for(let n=1;n<=nightRooms;n++)slots.push({id:`night-${n}`,room:`Urgencias ${String(n).padStart(2,'0')}`,shift:'Noche',rule:'URGENCIAS / EMERGENCIAS',cap:720,items:[],night:true});return slots}
function compatible(c,s){if(s.shift==='Noche')return ['emergente','urgente'].includes(c.status);if(s.cap===0)return false;let rule=norm(s.rule),sp=norm(c.specialty);if(rule.includes('disponible'))return true;let aliases={oftalmologia:['oftalmo'],otorrinolaringologia:['otorrino','orl'],ginecologia:['gineco'],maxilofacial:['maxilo'],obstetricia:['cesareas'],procedimientosdedolorybloqueos:['dolor','bloqueos'],cirugiavascularperiferica:['vascular']};let compact=sp.replace(/\s/g,''),terms=[sp,...(aliases[compact]||[])];let words=sp.split(/\s+/).filter(w=>w.length>3);return terms.some(t=>rule.includes(t))||words.some(w=>rule.includes(w))}function specialistAvailable(c,s){let surname=norm(c.specialist.split(',')[0]);let tokens=surname.split(/\s+/).filter(t=>t.length>3);return tokens.some(token=>norm(s.rule).includes(token))}
function selectedDate(){return $('date').value}function occupiedMinutes(items){return items.reduce((n,x)=>n+x.minutes,0)+Math.max(0,items.length-1)*turnover}function plan(){let slots=activeSlots(),scoped=cases.filter(c=>c.date===selectedDate());let sorted=[...scoped].sort((a,b)=>rank[a.status]-rank[b.status]||a.order-b.order);sorted.forEach(c=>{let candidates;if(['emergente','urgente'].includes(c.status)){candidates=slots.filter(s=>s.shift==='Noche')}else{let specialtySlots=slots.filter(s=>s.shift!=='Noche'&&compatible(c,s));let fixedSlots=specialtySlots.filter(s=>specialistAvailable(c,s));candidates=(fixedSlots.length?fixedSlots:specialtySlots).sort((a,b)=>a.shift.localeCompare(b.shift)||a.room.localeCompare(b.room))}let hit=candidates.map(s=>({slot:s,start:nextStart(s,c.minutes,slots)})).find(x=>x.start!==null);c.assignment=null;c.startMinute=null;c.endMinute=null;if(hit){c.startMinute=hit.start;c.endMinute=hit.start+c.minutes;c.assignment=`${hit.slot.room} · ${hit.slot.shift==='Noche'?'EXT':hit.slot.shift}`;hit.slot.items.push(c)}});render(slots,sorted)}
function displaySpecialty(rule){return String(rule||'—').split(/\r?\n/).map(line=>line.trim()).filter(line=>line&&!/^\(/.test(line)).map(line=>line.replace(/\s*\([^)]*\).*$/,'').trim()).filter(Boolean).join('\n')||'—'}function weekDates(){let d=new Date(`${selectedDate()}T12:00:00`),offset=(d.getDay()+6)%7;d.setDate(d.getDate()-offset);return days.map((day,i)=>{let x=new Date(d);x.setDate(d.getDate()+i);return {day,date:`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}})}function cellContent(room,shift,dayIndex,weekDate,slots){if(shift==='Noche'){if(room!=='SALA 01')return '—';let night=slots.filter(s=>s.shift==='Noche'),items=weekDate===selectedDate()?night.flatMap(s=>s.items.map(c=>({...c,nightRoom:s.room}))):[];return `URGENCIAS / EMERGENCIAS${items.map(c=>`<span class="matrix-case emergente">${esc(c.name)} · ${esc(c.nightRoom)}<br>Inicio / fin: ${caseTimes(c)}</span>`).join('')}`}let entry=regularities[$('site').value].find(x=>x[0]===room&&x[1]===shift),rule=entry&&entry[2][dayIndex]?entry[2][dayIndex]:'—',slot=slots.find(s=>s.room===room&&s.shift===shift),items=weekDate===selectedDate()?slot.items:[];return `${esc(rule==='—'?'—':displaySpecialty(rule)).replace(/\n/g,'<br>')}${items.map(c=>`<span class="matrix-case ${c.status}">${esc(c.name)} · ${c.minutes} min<br>Inicio / fin: ${caseTimes(c)}</span>`).join('')}`}
function render(slots,sorted){let week=weekDates(),rooms=[...new Set(regularities[$('site').value].map(x=>x[0]))];$('title').textContent=`${$('site').value} · semana de ${week[0].date}`;$('total').textContent=sorted.length;$('assigned').textContent=sorted.filter(c=>c.assignment).length;$('pending').textContent=sorted.filter(c=>!c.assignment).length;$('rooms').innerHTML=`<div class="matrix-wrap"><table class="matrix"><thead><tr><th rowspan="2">Sala</th><th rowspan="2">Jornada</th><th colspan="7">Dia</th></tr><tr>${week.map(w=>`<th class="${w.date===selectedDate()?'selected-day':''}">${w.day}<br><small>${w.date.slice(8)}</small></th>`).join('')}</tr></thead><tbody>${rooms.map(room=>['AM','PM','Noche'].map((shift,i)=>`<tr>${i===0?`<th class="room-name" rowspan="3">${room}</th>`:''}<th class="shift">${shift==='Noche'?'EXT':shift}<br><span class="shift-hours">${shift==='AM'?'07:00–13:00':shift==='PM'?'13:00–19:00':'19:00–07:00'}</span>${shift==='Noche'?'<br><span class="shift-hours">Dia siguiente</span>':''}</th>${week.map((w,di)=>`<td class="${w.date===selectedDate()?'selected-day':''} ${shift==='Noche'?'night-cell':''}">${cellContent(room,shift,di,w.date,slots)}</td>`).join('')}</tr>`).join('')).join('')}</tbody></table></div>`;$('queue').innerHTML=sorted.length?sorted.map(c=>`<tr><td><span class="tag ${c.status}">${c.status}</span></td><td>${esc(c.name)}<br><small>${esc(c.episode)} · ${esc(c.doc)}</small></td><td>${esc(c.specialty)}<br><small>${esc(c.anesthesia)} · CUPS ${esc(c.cups)}</small></td><td>${c.minutes} min</td><td>${c.assignment?esc(c.assignment)+'<br><strong>'+caseTimes(c)+'</strong>':'<span style="color:#a02929">Pendiente</span>'}</td><td><button class="danger" onclick="dropCase(${c.order})">Quitar</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No hay solicitudes para esta fecha.</td></tr>'}
function populateSpecialties(){const select=$('specialty');specialties.forEach(s=>{const option=document.createElement('option');option.value=s;option.textContent=s;select.append(option)});const specialist=$('specialist');specialists.forEach(s=>{const option=document.createElement('option');option.value=s;option.textContent=s;specialist.append(option)});const anesthesia=$('anesthesia');anesthesiaTypes.forEach(([code,label])=>{const option=document.createElement('option');option.value=`${code} · ${label}`;option.textContent=`${code} · ${label}`;anesthesia.append(option)});const cups=$('cups'),fragment=document.createDocumentFragment();cupsCatalog.forEach(([code,description])=>{const option=document.createElement('option');option.value=code;option.textContent=`${code} — ${description}`;fragment.append(option)});cups.append(fragment)}function today(){const d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${d.getFullYear()}-${m}-${day}`}$('date').value=today();$('caseForm').addEventListener('submit',e=>{e.preventDefault();cases.push({order:seq++,date:selectedDate(),name:$('name').value,doc:$('doc').value,episode:$('episode').value,status:$('status').value,anesthesia:$('anesthesia').value,specialty:$('specialty').value,specialist:$('specialist').value,minutes:+$('minutes').value,cups:$('cups').value});e.target.reset();$('status').value='electiva';plan()});$('site').onchange=plan;$('date').onchange=plan;$('clear').onclick=()=>{if(confirm('¿Eliminar las solicitudes ingresadas?')){cases=[];seq=1;plan()}};window.dropCase=n=>{cases=cases.filter(c=>c.order!==n);plan()};populateSpecialties();plan();

